export const contentArray = [
  "Table of Contents: Rankine Cycle",
  "1. Introduction to the Rankine Cycle",
  "   1.1 Definition and Purpose",
  "   1.2 Importance in Power Generation",
  "   1.3 Historical Background",
  "2. Basic Principles of Thermodynamics",
  "   2.1 Laws of Thermodynamics",
  "   2.2 Energy Conversion and Heat Transfer",
  "   2.3 Ideal vs. Real Processes",
  "3. Components of the Rankine Cycle",
  "   3.1 Boiler or Steam Generator",
  "      3.1.1 Function and Types",
  "         3.1.1.1 Jojo",
  "         3.1.1.2 Jojo",
  "      3.1.2 Heat Transfer Mechanisms",
  "   3.2 Turbine",
  "      3.2.1 Types and Working Principles",
  "      3.2.2 Efficiency and Performance",
  "   3.3 Condenser",
  "      3.3.1 Purpose and Operation",
  "      3.3.2 Cooling Methods",
  "   3.4 Pump",
  "      3.4.1 Function and Types",
  "      3.4.2 Work Input and Efficiency",
  "4. Rankine Cycle Processes",
  "   4.1 Vaporization or Boiling Process",
  "      4.1.1 Saturation and Superheated States",
  "      4.1.2 Heat Addition and Steam Quality",
  "   4.2 Expansion Process",
  "      4.2.1 Adiabatic and Isentropic Expansion",
  "      4.2.2 Work Output and Efficiency",
  "   4.3 Condensation Process",
  "      4.3.1 Heat Rejection and Cooling",
  "      4.3.2 Subcooling and Condenser Performance",
  "   4.4 Pumping Process",
  "      4.4.1 Compression and Work Input",
  "      4.4.2 Pressure Increase and Efficiency",
  "5. Rankine Cycle Analysis and Performance",
  "   5.1 Efficiency Calculation",
  "      5.1.1 Carnot Efficiency and Rankine Efficiency",
  "      5.1.2 Factors Affecting Efficiency",
  "   5.2 Heat Rate and Specific Steam Consumption",
  "      5.2.1 Definitions and Formulas",
  "      5.2.2 Importance in Power Plant Operation",
  "   5.3 Improving Rankine Cycle Performance",
  "      5.3.1 Regenerative Feed Heating",
  "      5.3.2 Reheating and Superheating",
  "      5.3.3 Combined Cycle Configurations",
  "6. Applications of the Rankine Cycle",
  "   6.1 Steam Power Plants",
  "      6.1.1 Thermal Power Plants",
  "      6.1.2 Nuclear Power Plants",
  "   6.2 Geothermal Power Plants",
  "   6.3 Waste Heat Recovery Systems",
  "   6.4 Solar Thermal Power Plants",
  "7. Challenges and Future Developments",
  "   7.1 Environmental Impact and Emissions",
  "   7.2 Integration with Renewable Energy Sources",
  "   7.3 Advanced Rankine Cycle Technologies",
  "      7.3.1 Supercritical and Ultra-Supercritical Cycles",
  "      7.3.2 Organic Rankine Cycle (ORC)",
  "      7.3.3 Combined Heat and Power (CHP) Systems",
  "8. Conclusion",
  "   8.1 Summary of Key Concepts",
  "   8.2 Importance and Applications",
  "   8.3 Future Prospects and Research Areas",
];

export const contentArrayNoSpace = [
  "Table of Contents: Rankine Cycle",
  "1. Introduction to the Rankine Cycle",
  "1.1 Definition and Purpose",
  "1.2 Importance in Power Generation",
  "1.3 Historical Background",
  "2. Basic Principles of Thermodynamics",
  "2.1 Laws of Thermodynamics",
  "2.2 Energy Conversion and Heat Transfer",
  "2.3 Ideal vs. Real Processes",
  "3. Components of the Rankine Cycle",
  "3.1 Boiler or Steam Generator",
  "3.1.1 Function and Types",
  "3.1.1.1 Jojo",
  "3.1.1.2 Jojo",
  "3.1.2 Heat Transfer Mechanisms",
  "3.2 Turbine",
  "3.2.1 Types and Working Principles",
  "3.2.2 Efficiency and Performance",
  "3.3 Condenser",
  "3.3.1 Purpose and Operation",
  "3.3.2 Cooling Methods",
  "3.4 Pump",
  "3.4.1 Function and Types",
  "3.4.2 Work Input and Efficiency",
  "4. Rankine Cycle Processes",
  "4.1 Vaporization or Boiling Process",
  "4.1.1 Saturation and Superheated States",
  "4.1.2 Heat Addition and Steam Quality",
  "4.2 Expansion Process",
  "4.2.1 Adiabatic and Isentropic Expansion",
  "4.2.2 Work Output and Efficiency",
  "4.3 Condensation Process",
  "4.3.1 Heat Rejection and Cooling",
  "4.3.2 Subcooling and Condenser Performance",
  "4.4 Pumping Process",
  "4.4.1 Compression and Work Input",
  "4.4.2 Pressure Increase and Efficiency",
  "5. Rankine Cycle Analysis and Performance",
  "5.1 Efficiency Calculation",
  "5.1.1 Carnot Efficiency and Rankine Efficiency",
  "5.1.2 Factors Affecting Efficiency",
  "5.2 Heat Rate and Specific Steam Consumption",
  "5.2.1 Definitions and Formulas",
  "5.2.2 Importance in Power Plant Operation",
  "5.3 Improving Rankine Cycle Performance",
  "5.3.1 Regenerative Feed Heating",
  "5.3.2 Reheating and Superheating",
  "5.3.3 Combined Cycle Configurations",
  "6. Applications of the Rankine Cycle",
  "6.1 Steam Power Plants",
  "6.1.1 Thermal Power Plants",
  "6.1.2 Nuclear Power Plants",
  "6.2 Geothermal Power Plants",
  "6.3 Waste Heat Recovery Systems",
  "6.4 Solar Thermal Power Plants",
  "7. Challenges and Future Developments",
  "7.1 Environmental Impact and Emissions",
  "7.2 Integration with Renewable Energy Sources",
  "7.3 Advanced Rankine Cycle Technologies",
  "7.3.1 Supercritical and Ultra-Supercritical Cycles",
  "7.3.2 Organic Rankine Cycle (ORC)",
  "7.3.3 Combined Heat and Power (CHP) Systems",
  "8. Conclusion",
  "8.1 Summary of Key Concepts",
  "8.2 Importance and Applications",
  "8.3 Future Prospects and Research Areas",
];

export const resourcesDataString =
  "Table of Contents: Material Science\n\n1. Introduction to Material Science\n   1.1 Definition and Scope of Material Science\n   1.2 Importance and Applications of Material Science\n   1.3 Historical Overview of Material Science\n\n2. Atomic Structure and Bonding\n   2.1 Atomic Structure\n      2.1.1 Subatomic Particles\n      2.1.2 Atomic Models\n   2.2 Chemical Bonding\n      2.2.1 Types of Chemical Bonds\n      2.2.2 Ionic Bonding\n      2.2.3 Covalent Bonding\n      2.2.4 Metallic Bonding\n\n3. Crystal Structure and Defects\n   3.1 Introduction to Crystals\n   3.2 Crystal Lattices\n      3.2.1 Unit Cells\n      3.2.2 Crystal Systems\n   3.3 Crystallographic Directions and Planes\n   3.4 Crystal Defects\n      3.4.1 Point Defects\n      3.4.2 Line Defects\n      3.4.3 Surface Defects\n      3.4.4 Volume Defects\n\n4. Mechanical Properties of Materials\n   4.1 Stress and Strain\n      4.1.1 Types of Stress and Strain\n      4.1.2 Hooke's Law\n   4.2 Elastic Deformation\n   4.3 Plastic Deformation\n      4.3.1 Slip and Dislocations\n      4.3.2 Strengthening Mechanisms\n   4.4 Failure of Materials\n      4.4.1 Fracture\n      4.4.2 Fatigue\n      4.4.3 Creep\n\n5. Phase Diagrams and Phase Transformations\n   5.1 Introduction to Phase Diagrams\n   5.2 Binary Phase Diagrams\n      5.2.1 Components and Phases\n      5.2.2 Eutectic and Peritectic Reactions\n      5.2.3 Solid Solutions\n   5.3 Phase Transformations\n      5.3.1 Diffusion and Nucleation\n      5.3.2 Solidification\n      5.3.3 Precipitation\n      5.3.4 Martensitic Transformation\n\n6. Thermal Properties of Materials\n   6.1 Heat Capacity and Thermal Conductivity\n   6.2 Thermal Expansion\n   6.3 Phase Transitions and Thermal Analysis\n      6.3.1 Differential Scanning Calorimetry (DSC)\n      6.3.2 Thermogravimetric Analysis (TGA)\n      6.3.3 Thermal Mechanical Analysis (TMA)\n\n7. Electrical and Magnetic Properties of Materials\n   7.1 Electrical Conductivity\n      7.1.1 Conductors, Insulators, and Semiconductors\n      7.1.2 Band Theory of Solids\n   7.2 Dielectric Properties\n      7.2.1 Polarization and Permittivity\n      7.2.2 Ferroelectricity\n   7.3 Magnetic Properties\n      7.3.1 Magnetism and Magnetic Fields\n      7.3.2 Ferromagnetism, Paramagnetism, and Diamagnetism\n\n8. Optical Properties of Materials\n   8.1 Absorption, Reflection, and Transmission of Light\n   8.2 Refractive Index and Snell's Law\n   8.3 Optical Materials and Devices\n      8.3.1 Photonic Crystals\n      8.3.2 Optical Fibers\n      8.3.3 Lasers and LEDs\n\n9. Materials Processing and Manufacturing\n   9.1 Casting and Solidification Processes\n   9.2 Forming and Shaping Processes\n      9.2.1 Rolling, Extrusion, and Drawing\n      9.2.2 Sheet Metal Forming\n   9.3 Machining and Joining Processes\n      9.3.1 Cutting and Grinding\n      9.3.2 Welding and Brazing\n   9.4 Additive Manufacturing\n      9.4.1 3D Printing\n      9.4.2 Selective Laser Sintering (SLS)\n\n10. Materials Characterization Techniques\n    10.1 Microscopy Techniques\n       10.1.1 Optical Microscopy\n       10.1.2 Scanning Electron Microscopy (SEM)\n       10.1.3 Transmission Electron Microscopy (TEM)\n    10.2 X-ray Diffraction (XRD)\n    10.3 Spectroscopy Techniques\n       10.3.1 Fourier Transform Infrared Spectroscopy (FTIR)\n       10.3.2 Raman Spectroscopy\n       10.3.3 Nuclear Magnetic Resonance (NMR)\n\n11. Nanomaterials and Nanotechnology\n    11.1 Introduction to Nanomaterials\n    11.2 Synthesis and Properties of Nanomaterials\n       11.2.1 Bottom-up and Top-down Approaches\n       11.2.2 Quantum Dots and Nanowires\n    11.3 Applications of Nanotechnology\n       11.3.1 Nanoelectronics and Nanophotonics\n       11.3.2 Nanomedicine and Drug Delivery\n\n12. Biomaterials\n    12.1 Introduction to Biomaterials\n    12.2 Types of Biomaterials\n       12.2.1 Metals, Polymers, and Ceramics\n       12.2.2 Biocompatibility and Bioactivity\n    12.3 Applications of Biomaterials\n       12.3.1 Implants and Prosthetics\n       12.3.2 Tissue Engineering and Regenerative Medicine\n\n13. Environmental and Sustainable Materials\n    13.1 Materials Recycling and Waste Management\n    13.2 Green Materials and Sustainable Design\n       13.2.1 Life Cycle Assessment (LCA)\n       13.2.2 Renewable Energy Materials\n\n14. Future Trends and Emerging Materials\n    14.1 Advanced Materials and Technologies\n    14.2 Smart Materials and Shape Memory Alloys\n    14.3 Self-healing Materials\n    14.4 Carbon Nanotubes and Graphene\n\n15. Conclusion and Future Directions in Material Science\n\nNote: This table of contents provides a comprehensive overview of the topics covered in the field of Material Science. Each section can be further expanded into detailed chapters and subtopics for a complete textbook.";
